### ISSUE TITLE
texelFetchBuffer() instead of texture()

### ISSUE THREAD

**Issue by raganmd** [kamindustries/td-scope#1]
You may consider changing your approach here to use a `samplerBuffer` instead of a just a sampler. In doing some preliminary testing the reported GPU cooktime drops by about 4ms based on that change.

```GLSL
// syntax for declaring the sampler Buffer
uniform samplerBuffer u_signal_buf;

// syntax for using the texelFetchBuffer() method
vec4 sig = texelFetchBuffer(u_signal_buf, gl_VertexID);
```

On the GLSL Material that looks like:
![texelfetchbuffer](https://user-images.githubusercontent.com/11582808/39594412-8002b1b8-4ec1-11e8-90ca-07057cae89d0.PNG)

I haven't done any significant testing to see if that breaks anything in particular, but it might be worth experimenting with - it should also mean that you no longer need to convert from CHOP to TOP in order to sample your texture with the GLSL Material.

**Comment by kamindustries** [comment]
Awesome, thanks Mr. Ragan. I went ahead and switched over to a texture buffer. If I had a nickel for every OpenGL texture object...
